### ISSUE TITLE
Нужны отступы для иконок

### ISSUE THREAD

**Issue by kazah96** [Nick4Dead/Blog#1]
![изображение](https://user-images.githubusercontent.com/11855225/159118724-e5e5441f-49c9-478f-bab4-3862a3b41a97.png)

**Comment by kazah96** [comment]
![изображение](https://user-images.githubusercontent.com/11855225/159119357-6e597628-529d-4a5b-ab6f-28029c8a4ab8.png)

Косяк с отступами

**Comment by ezzyflex** [comment]
![image](https://user-images.githubusercontent.com/101928954/159119506-96d4e159-bee3-4a31-b2e2-7881ce641075.png)

**Comment by Nick4Dead** [comment]
Фиксанул

**Comment by ezzyflex** [comment]
все оке
